kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 4000
    protocol: TCP
  # - containerPort: 6379
  #   hostPort: 6379
  #   protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 6379
    hostPort: 6379
  - containerPort: 26379
    hostPort: 26379
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 6379
    hostPort: 6380
  - containerPort: 26379
    hostPort: 26380
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 6379
    hostPort: 6381
  - containerPort: 26379
    hostPort: 26381
    protocol: TCP
